#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hooks..."
echo "-----------------------------"
echo "Running build..."
yarn build
echo "Running lint-staged..."
npx lint-staged
